/* eslint-disable prettier/prettier */
export const iconTypes = [
  'b2b_icon-arrow-down',
  'b2b_icon-arrow-left',
  'b2b_icon-arrow-right',
  'b2b_icon-arrow-up',
  'b2b_icon-basket',
  'b2b_icon-check',
  'b2b_icon-close',
  'b2b_icon-delete',
  'b2b_icon-error-hint',
  'b2b_icon-filter',
  'b2b_icon-info-hint',
  'b2b_icon-info',
  'b2b_icon-leaving-page',
  'b2b_icon-minus',
  'b2b_icon-pin',
  'b2b_icon-plus',
  'b2b_icon-question-hint',
  'b2b_icon-question',
  'b2b_icon-rating-empty',
  'b2b_icon-rating-filled',
  'b2b_icon-rating-half',
  'b2b_icon-refresh',
  'b2b_icon-reply',
  'b2b_icon-smiley-positive',
  'b2b_icon-sort-ascending',
  'b2b_icon-sort-descending',
  'b2b_icon-sort',
  'b2b_icon-success-hint',
  'b2b_icon-trend-down',
  'b2b_icon-trend-up',
  'b2b_icon-warning-hint',
  'b2b_icon-wishlist-active',
  'b2b_icon-wishlist',
] as const;
export type IconName = (typeof iconTypes)[number];
